# Generated by Django 4.0.6 on 2023-02-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commands_list',
            name='adress',
            field=models.CharField(max_length=250),
        ),
    ]
