# Generated by Django 4.0.6 on 2023-02-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
