# Generated by Django 4.0.6 on 2023-01-30 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_amount_alter_products_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='categories',
            new_name='categorie',
        ),
    ]
