# Generated by Django 4.0.6 on 2023-02-18 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_products_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='name',
            new_name='nameProduct',
        ),
    ]
