# Generated by Django 4.0.6 on 2023-02-18 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_name_products_nameproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='categorie',
            new_name='categorieOfProduct',
        ),
    ]
